-- MySQL Script generated by MySQL Workbench
-- Fri Sep  9 18:22:10 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema marko_yaminsky
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema marko_yaminsky
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `marko_yaminsky` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `marko_yaminsky` ;

-- -----------------------------------------------------
-- Table `marko_yaminsky`.`country`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `marko_yaminsky`.`country` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idcountry_UNIQUE` (`id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `marko_yaminsky`.`client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `marko_yaminsky`.`client` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(40) NOT NULL,
  `person` ENUM('legal', 'physical') NOT NULL,
  `country_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_client_country1_idx` (`country_id` ASC),
  CONSTRAINT `fk_client_country1`
    FOREIGN KEY (`country_id`)
    REFERENCES `marko_yaminsky`.`country` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `marko_yaminsky`.`bank`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `marko_yaminsky`.`bank` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL,
  `country_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  INDEX `fk_bank_country1_idx` (`country_id` ASC),
  CONSTRAINT `fk_bank_country1`
    FOREIGN KEY (`country_id`)
    REFERENCES `marko_yaminsky`.`country` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `marko_yaminsky`.`account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `marko_yaminsky`.`account` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `requisites` VARCHAR(40) NOT NULL,
  `client_id` INT UNSIGNED NOT NULL,
  `bank_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `requisites_UNIQUE` (`requisites` ASC),
  INDEX `fk_account_client1_idx` (`client_id` ASC),
  INDEX `fk_account_bank1_idx` (`bank_id` ASC),
  CONSTRAINT `fk_account_client1`
    FOREIGN KEY (`client_id`)
    REFERENCES `marko_yaminsky`.`client` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_account_bank1`
    FOREIGN KEY (`bank_id`)
    REFERENCES `marko_yaminsky`.`bank` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `marko_yaminsky`.`transaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `marko_yaminsky`.`transaction` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `event` VARCHAR(50) NULL DEFAULT NULL,
  `price` INT NOT NULL,
  `buyer_account_id` INT UNSIGNED NOT NULL,
  `seller_account_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idtransaction_UNIQUE` (`id` ASC),
  INDEX `fk_transaction_account1_idx` (`buyer_account_id` ASC),
  INDEX `fk_transaction_account2_idx` (`seller_account_id` ASC),
  CONSTRAINT `fk_transaction_account1`
    FOREIGN KEY (`buyer_account_id`)
    REFERENCES `marko_yaminsky`.`account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transaction_account2`
    FOREIGN KEY (`seller_account_id`)
    REFERENCES `marko_yaminsky`.`account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `marko_yaminsky`.`bank_has_client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `marko_yaminsky`.`bank_has_client` (
  `bank_id` INT UNSIGNED NOT NULL,
  `client_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`bank_id`, `client_id`),
  INDEX `fk_bank_has_client_client1_idx` (`client_id` ASC),
  INDEX `fk_bank_has_client_bank_idx` (`bank_id` ASC) VISIBLE,
  CONSTRAINT `fk_bank_has_client_bank`
    FOREIGN KEY (`bank_id`)
    REFERENCES `marko_yaminsky`.`bank` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bank_has_client_client1`
    FOREIGN KEY (`client_id`)
    REFERENCES `marko_yaminsky`.`client` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
